on:
  pull_request:
    branches:
      - main

name: run lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
